<?php
        return array (
  'logo' => 'admin/assets/images/brand/bg_logo.jpg',
  'logo_login' => 'admin/assets/images/brand/logo.png',
  'app_name' => 'Ushas',
  'copyright' => 'Copyright &copy; 2022  <a href=\'\'>Ushas</a>. Designed by <a href=\'https://estrrado.com/\' target=\'_blank\'>Estrrado</a> All rights reserved.',
  'dashboard_bg' => '#302F32',
  'menu_icon_color' => '#302F32',
  'btn_secondary' => '#6958be',
  'link_color' => '#705ec8',
  'bg_primary_color' => '#302F32',
  'bg_primary_image' => '',
  'active_link' => '#705ec8',
  'back_to_top' => '#6958be',
  'btn_primary' => '#6958be',
  'btn_info' => '#5b7fff',
  'mailgun' => 
  array (
    'domain' => NULL,
    'secret' => NULL,
    'endpoint' => 'api.mailgun.net',
  ),
  'base_url' => 'https://qa-ushas.estrradoweb.com',
  'm_lang' => 'yes',
  'm_currency' => 'yes',
  'prod_type' => 'from_api',
  'payment_gateway' => 'stripe',
  'shipping_md' => 'fedex',
  'return_flow' => 'flow_2',
  'seller_panel' => 'yes',
  'cust_approval' => 'yes',
  'cust_credits' => 'yes',
  'cust_referral' => 'no',
  'extra_fields' => 'no',
  'brands' => 'no',
  'prod_return' => 'no',
  'refund' => 'no',
  'discount' => 'no',
  'rewards' => 'yes',
  'blog' => 'yes',
  'support_ticket' => 'no',
  'loyality_points' => 'no',
  'branches' => 'no',
);